#!/usr/bin/env ansible-playbook
- name: Disable HDMI Port
  lineinfile:
    path: /etc/rc.local
    regexp: '^/usr/bin/tvservice'
    line: '/usr/bin/tvservice -o'
    insertafter: '^exit'
    state: present
