#!/usr/bin/env ansible-playbook
---
- name: basic setup
  hosts: raspios
  become: yes

  vars_files:
    - defaults/main.yml
    - defaults/secrets.yml

  vars:
    # remove python ansible warning
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  pre_tasks:
  - name: Pull rpi visualizer image
    community.docker.docker_image:
      name: alexellis2/visualizer-arm:latest
      source: pull

  roles:
    - { role: dockerswarm }

  # tasks:
  # - name: Run rpi visualizer service
  #   docker_swarm_service:
  #     name: viz
  #     image: alexellis2/visualizer-arm:latest
  #     constraints:
  #       - node.role == manager
  #     mounts:
  #       - source: /var/run/docker.sock
  #         target: /var/run/docker.sock
  #         type: bind
  #     publish:
  #       - published_port: 8080
  #         target_port: 8080
  #         protocol: tcp
  #         mode: host
